version: '3.9'

services:
  fastapi:
    build: .
    container_name: fastapi_cont
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --reload
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - ./:/project/

  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    env_file:
      - .env

  redis:
    image: redis:alpine
    container_name: redis_cont
